services:
  go-service:
    build:
      context: ./go-service
      dockerfile: Dockerfile
    container_name: loresmith-go-service
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres
      - python-service

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    container_name: loresmith-python-service
    ports:
      - "50051:50051"
    env_file: .env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./python-service/prompts:/app/prompts
      - ./frontend/public/generated:/app/generated

  redis:
    image: redis:8
    container_name: loresmith-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg12
    container_name: loresmith-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

  test-postgres:
    image: pgvector/pgvector:pg16
    container_name: loresmith-test-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${TEST_POSTGRES_DB}
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    profiles:
      - test

volumes:
  postgres_data:
  test_postgres_data:
